# This code has been generated by the pocket_coffea CLI 0.9.6.
import awkward as ak
from pocket_coffea.lib.cut_definition import Cut
from numpy import sqrt

notau = Cut(
    name="notau",
    params={},
    function=lambda events, params, **kwargs: (
        ak.sum((abs(events.LHEPart.pdgId) == 15), axis=1) == 0
    )
)

def vbs_cuts(events, params, **kwargs):
    mask = events.mll > params["mll"]
    pdgProd = abs(events.LeptonGood.pdgId[:, 0] * events.LeptonGood.pdgId[:, 1])
    mask_Mz = ak.where(pdgProd != 11*13, abs(events.mll - 90.) > params["deltaMZ"], ak.ones_like(events.mll) > 0.)
    mask = mask & mask_Mz
    max_Zepp = ak.where(events.Zeppl1_vbs > events.Zeppl2_vbs, events.Zeppl1_vbs, events.Zeppl2_vbs)
    mask = mask & (events.PuppiMET.pt > params["MET"])
    mask = mask & (max_Zepp < params["max_Zeppl_vbs"])
    mask = mask & (events.mjj_vbs > params["mjj_vbs"])
    mask = mask & (events.deltaeta_vbs > params["detajj_vbs"])
    return mask

vbs_presel = Cut(
    name="vbs_presel",
    params={"mll": 20.,
            "mjj_vbs": 500.,
            "detajj_vbs": 2.5,
            "max_Zeppl_vbs": 0.75,
            "MET": 30.,
            "deltaMZ": 15.
            },
    function=vbs_cuts
)


vbs_presel_looser = Cut(
    name="vbs_presel",
    params={"mll": 10.,
            "mjj_vbs": 200.,
            "detajj_vbs": 0.,
            "max_Zeppl_vbs": 1.5,
            "MET": 15.,
            "deltaMZ": 0.
            },
    function=vbs_cuts
)



def ss_cut(events, params, **kwargs):
    pdgProd = events.LeptonGood.pdgId[:, 0] * events.LeptonGood.pdgId[:, 1]
    mask = pdgProd > 0
    return mask

samesign = Cut(
    name="samesign",
    params={},
    function=ss_cut
)
